"""Seed data based on real Australian cycling events and venues.

This data is used when live scraping fails (e.g., due to bot protection).
Events are modelled on actual races from AusCycling, WCMCC, and other clubs.
"""

from .base import CyclingEvent


def get_seed_events() -> list[CyclingEvent]:
    return [
        # === WEST COAST MASTERS CC (WA) ===
        CyclingEvent(
            name="WCMCC Bibra Lake Club Race",
            date="2026-03-01",
            end_date=None,
            venue="Bibra Lake Circuit",
            address="Bibra Lake, WA 6163",
            lat=-32.0903,
            lng=115.8226,
            discipline="criterium",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Graded criterium on the 950m Bibra Lake circuit. All grades.",
        ),
        CyclingEvent(
            name="WCMCC Kewdale Graded Criterium",
            date="2026-03-08",
            end_date=None,
            venue="Kewdale Circuit",
            address="Kewdale, WA 6105",
            lat=-31.9750,
            lng=115.9500,
            discipline="criterium",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Graded criterium on the 1.5km Kewdale circuit.",
        ),
        CyclingEvent(
            name="WCMCC Casuarina Road Race",
            date="2026-03-15",
            end_date=None,
            venue="Casuarina Short Road Course",
            address="502 Orton Rd, Casuarina WA 6167",
            lat=-32.2200,
            lng=115.8600,
            discipline="road",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Graded road race. Masters categories.",
        ),
        CyclingEvent(
            name="WCMCC Motorplex Criterium",
            date="2026-03-22",
            end_date=None,
            venue="Perth Motorplex",
            address="Perth Motorplex, Kwinana WA 6167",
            lat=-32.2378,
            lng=115.8015,
            discipline="criterium",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Criterium racing on the 1.5km Motorplex circuit.",
        ),
        CyclingEvent(
            name="WCMCC Rockingham Club Race",
            date="2026-03-29",
            end_date=None,
            venue="Rockingham Circuit",
            address="Rockingham, WA 6168",
            lat=-32.2772,
            lng=115.7302,
            discipline="criterium",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Graded criterium on the 1.7km Rockingham circuit.",
        ),
        CyclingEvent(
            name="WCMCC Wangara Graded Criterium",
            date="2026-04-05",
            end_date=None,
            venue="Wangara Circuit",
            address="Wangara, WA 6065",
            lat=-31.7900,
            lng=115.8300,
            discipline="criterium",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Graded criterium on the 1.3km Wangara circuit.",
        ),
        CyclingEvent(
            name="WCMCC Perth Airport DRMC Race",
            date="2026-04-12",
            end_date=None,
            venue="Perth Airport DRMC",
            address="Perth Airport, WA 6105",
            lat=-31.9385,
            lng=115.9672,
            discipline="criterium",
            organiser="West Coast Masters CC",
            source="wcmcc",
            url="https://entryboss.cc/calendar/westcoastmasterscc",
            state="WA",
            description="Graded criterium on the 1.5km Perth Airport DRMC circuit.",
        ),

        # === AUSCYCLING WA EVENTS ===
        CyclingEvent(
            name="WA State Road Championships",
            date="2026-04-18",
            end_date="2026-04-19",
            venue="Collie",
            address="Collie, WA 6225",
            lat=-33.3608,
            lng=116.1522,
            discipline="road",
            organiser="AusCycling WA",
            source="auscycling",
            url="https://auscycling.org.au/wa/events",
            state="WA",
            description="State road race and time trial championships.",
        ),
        CyclingEvent(
            name="WA State Track Championships",
            date="2026-05-02",
            end_date="2026-05-03",
            venue="SpeedDome",
            address="Midvale, WA 6056",
            lat=-31.8870,
            lng=116.0320,
            discipline="track",
            organiser="AusCycling WA",
            source="auscycling",
            url="https://auscycling.org.au/wa/events",
            state="WA",
            description="State track cycling championships at the SpeedDome velodrome.",
        ),
        CyclingEvent(
            name="Dwellingup 100 MTB",
            date="2026-05-17",
            end_date=None,
            venue="Dwellingup Trails",
            address="Dwellingup, WA 6213",
            lat=-32.7130,
            lng=116.0620,
            discipline="mtb",
            organiser="AusCycling WA",
            source="auscycling",
            url="https://auscycling.org.au/wa/events",
            state="WA",
            description="100km mountain bike endurance event through Dwellingup trails.",
        ),
        CyclingEvent(
            name="Perth Hills Gravel Fondo",
            date="2026-04-25",
            end_date=None,
            venue="Mundaring",
            address="Mundaring, WA 6073",
            lat=-31.9013,
            lng=116.1685,
            discipline="gravel",
            organiser="AusCycling WA",
            source="auscycling",
            url="https://auscycling.org.au/wa/events",
            state="WA",
            description="Gravel riding through the Perth Hills. 60km and 100km options.",
        ),

        # === AUSCYCLING NATIONAL / OTHER STATES ===
        CyclingEvent(
            name="National Road Championships",
            date="2026-01-08",
            end_date="2026-01-12",
            venue="Ballarat",
            address="Ballarat, VIC 3350",
            lat=-37.5622,
            lng=143.8503,
            discipline="road",
            organiser="AusCycling",
            source="auscycling",
            url="https://auscycling.org.au/nat/events",
            state="VIC",
            description="Australian National Road Cycling Championships. Elite, U23, Junior and Masters.",
        ),
        CyclingEvent(
            name="Tour Down Under",
            date="2026-01-20",
            end_date="2026-01-25",
            venue="Adelaide",
            address="Adelaide, SA 5000",
            lat=-34.9285,
            lng=138.6007,
            discipline="road",
            organiser="AusCycling / Events SA",
            source="auscycling",
            url="https://auscycling.org.au/sa/events",
            state="SA",
            description="UCI WorldTour stage race through the Adelaide Hills and Barossa Valley.",
        ),
        CyclingEvent(
            name="National Track Championships",
            date="2026-02-12",
            end_date="2026-02-15",
            venue="Anna Meares Velodrome",
            address="Chandler, QLD 4155",
            lat=-27.5167,
            lng=153.1500,
            discipline="track",
            organiser="AusCycling",
            source="auscycling",
            url="https://auscycling.org.au/nat/events",
            state="QLD",
            description="Australian National Track Cycling Championships.",
        ),
        CyclingEvent(
            name="Cape to Cape MTB",
            date="2026-10-15",
            end_date="2026-10-18",
            venue="Margaret River",
            address="Margaret River, WA 6285",
            lat=-33.9537,
            lng=115.0753,
            discipline="mtb",
            organiser="Cape to Cape MTB",
            source="auscycling",
            url="https://auscycling.org.au/wa/events",
            state="WA",
            description="4-day mountain bike stage race through the Cape to Cape region.",
        ),
        CyclingEvent(
            name="Cadel Evans Great Ocean Road Race",
            date="2026-02-01",
            end_date=None,
            venue="Geelong",
            address="Geelong, VIC 3220",
            lat=-38.1499,
            lng=144.3617,
            discipline="road",
            organiser="AusCycling",
            source="auscycling",
            url="https://auscycling.org.au/vic/events",
            state="VIC",
            description="UCI ProSeries one-day road race along the Great Ocean Road.",
        ),
        CyclingEvent(
            name="Amy's Gran Fondo",
            date="2026-03-08",
            end_date=None,
            venue="Lorne",
            address="Lorne, VIC 3232",
            lat=-38.5421,
            lng=143.9788,
            discipline="road",
            organiser="AusCycling / Amy Gillett Foundation",
            source="auscycling",
            url="https://auscycling.org.au/vic/events",
            state="VIC",
            description="Mass participation road cycling event. 42km, 76km, and 104km courses.",
        ),
        CyclingEvent(
            name="NSW State Criterium Championships",
            date="2026-03-14",
            end_date=None,
            venue="Homebush",
            address="Sydney Olympic Park, NSW 2127",
            lat=-33.8469,
            lng=151.0694,
            discipline="criterium",
            organiser="AusCycling NSW",
            source="auscycling",
            url="https://auscycling.org.au/nsw/events",
            state="NSW",
            description="NSW State Criterium Championships at Sydney Olympic Park.",
        ),
        CyclingEvent(
            name="Melbourne to Warrnambool",
            date="2026-10-10",
            end_date=None,
            venue="Warrnambool",
            address="Warrnambool, VIC 3280",
            lat=-38.3818,
            lng=142.4877,
            discipline="road",
            organiser="Warrnambool Cycling Club",
            source="auscycling",
            url="https://auscycling.org.au/vic/events",
            state="VIC",
            description="Australia's oldest one-day cycling classic. 265km from Melbourne.",
        ),
        CyclingEvent(
            name="Grafton to Inverell Classic",
            date="2026-05-09",
            end_date=None,
            venue="Inverell",
            address="Inverell, NSW 2360",
            lat=-29.7752,
            lng=151.1139,
            discipline="road",
            organiser="Inverell Cycle Club",
            source="auscycling",
            url="https://auscycling.org.au/nsw/events",
            state="NSW",
            description="228km classic one-day road race through the NSW Northern Tablelands.",
        ),
        CyclingEvent(
            name="National BMX Championships",
            date="2026-04-02",
            end_date="2026-04-05",
            venue="Sleeman Sports Complex",
            address="Chandler, QLD 4155",
            lat=-27.5200,
            lng=153.1530,
            discipline="bmx",
            organiser="AusCycling",
            source="auscycling",
            url="https://auscycling.org.au/nat/events",
            state="QLD",
            description="National BMX Racing Championships.",
        ),
        CyclingEvent(
            name="Gravel Grit Dirty River Ride",
            date="2026-06-14",
            end_date=None,
            venue="Yarra Valley",
            address="Warburton, VIC 3799",
            lat=-37.7530,
            lng=145.6910,
            discipline="gravel",
            organiser="Gravel Grit",
            source="auscycling",
            url="https://auscycling.org.au/vic/events",
            state="VIC",
            description="Gravel riding event through the Yarra Ranges. 50km and 100km options.",
        ),
        CyclingEvent(
            name="Nowra Cyclocross",
            date="2026-07-19",
            end_date=None,
            venue="Nowra Showground",
            address="Nowra, NSW 2541",
            lat=-34.8818,
            lng=150.6003,
            discipline="cyclocross",
            organiser="Shoalhaven Cycling Club",
            source="auscycling",
            url="https://auscycling.org.au/nsw/events",
            state="NSW",
            description="Cyclocross racing at Nowra Showground.",
        ),
        CyclingEvent(
            name="SA State Road Championships",
            date="2026-03-28",
            end_date="2026-03-29",
            venue="Clare Valley",
            address="Clare, SA 5453",
            lat=-33.8369,
            lng=138.6060,
            discipline="road",
            organiser="AusCycling SA",
            source="auscycling",
            url="https://auscycling.org.au/sa/events",
            state="SA",
            description="South Australian State Road Championships.",
        ),
        CyclingEvent(
            name="Brisbane Cycling Festival Track",
            date="2026-03-18",
            end_date="2026-03-22",
            venue="Anna Meares Velodrome",
            address="Chandler, QLD 4155",
            lat=-27.5167,
            lng=153.1500,
            discipline="track",
            organiser="AusCycling QLD",
            source="auscycling",
            url="https://auscycling.org.au/qld/events",
            state="QLD",
            description="Track cycling festival with international and domestic racing.",
        ),
        CyclingEvent(
            name="Tasmania MTB Enduro",
            date="2026-04-11",
            end_date="2026-04-12",
            venue="Derby",
            address="Derby, TAS 7264",
            lat=-41.1490,
            lng=147.7910,
            discipline="mtb",
            organiser="AusCycling TAS",
            source="auscycling",
            url="https://auscycling.org.au/tas/events",
            state="TAS",
            description="Mountain bike enduro racing on world-class Derby trails.",
        ),
    ]
